name: CI/CD for sibylla

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod download
        working-directory: sibylla_service

      - name: Run tests
        run: go test ./...
        working-directory: sibylla_service

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o sibylla ./cmd
        working-directory: sibylla_service

      - name: Copy static files
        run: mkdir -p static && cp -r static ./static/
        working-directory: sibylla_service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Copy files to server
        uses: appleboy/scp-action@v0.0.4
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "./sibylla_service ./sibylla_service/static/"
          target: "/root/"

      - name: Restart service on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            sudo systemctl restart sibylla
